LINKERSCRIPT = qpe.ld
LIB_S2L = $(PREFIX_LIB_DIR)/s2-lib
LIBRARIES += $(LIB_S2L)
LIBS += -ls2
LIB_SPIKE_COMMS = $(PREFIX_LIB_DIR)/spike-comms-lib
LIBRARIES += $(LIB_SPIKE_COMMS)
LIBS += -lspike-comms
ROUTING_SETTINGS ?= MC_ROUTING SINGLE_CHIP=1
DEFS += $(ROUTING_SETTINGS)
$(info DEFS is: $(DEFS))
# include ../Makefile.default
# temporarily hardcoded:
# include /home/weih/updated_pyspinnaker2/py-spinnaker2/src/spinnaker2/libs/chip/app-pe/s2app/Makefile.default
include $(DEFAULT_MAKEFILE_PATH)/Makefile.default