LINKERSCRIPT = qpe.ld

LIB_S2L = $(PREFIX_LIB_DIR)/s2-lib
LIBRARIES += $(LIB_S2L)
LIBS += -ls2
#include ../Makefile.default.with_s2lib
include $(S2SIM2LABAPP_ROOT_PATH)/chip/app-pe/s2app/Makefile.default  # has to be adjusted to point to default from any directory the generated code is placed in
