LINKERSCRIPT = qpe.ld
LIB_S2L = $(PREFIX_LIB_DIR)/s2-lib
LIBRARIES += $(LIB_S2L)
LIBS += -ls2
LIB_SPIKE_COMMS = $(PREFIX_LIB_DIR)/spike-comms-lib
LIBRARIES += $(LIB_SPIKE_COMMS)
LIBS += -lspike-comms
ROUTING_SETTINGS ?= MC_ROUTING SINGLE_CHIP=1
DEFS += $(ROUTING_SETTINGS)
$(info DEFS is: $(DEFS))
#include ../Makefile.default.with_s2lib
include ../Makefile.default