MODELS = {% for neuron in neurons %}{{neuron.get_name()}} {% endfor %}

all:
	for d in $(MODELS); do $(MAKE) -C $$d || exit $$?; done

clean:
	for d in $(MODELS); do $(MAKE) -C $$d clean || exit $$?; done
