"""A very simple test script, that will instantiate all the models generated by NESTML and run a NEST simulation. This is used for integration testing in Travis-CI, to ensure that all the generated models can be instantiated. No connectivity or stimuli are defined."""

import numpy as np
import nest

def strip_suffix(l, suffix):
        new_l = []
        for n in l:
                if n[-len(suffix):] == suffix:
                        n = n[:-len(suffix)]
                new_l.append(n)
        return new_l


nest.set_verbosity("M_ALL")
nest.Install("nestmlmodule")

models = nest.Models(mtype="nodes")
neuron_models = [m for m in models if str(nest.GetDefaults(m, "element_type")) == "neuron"]
_neuron_models = strip_suffix(neuron_models, "_neuron")

nestml_unit_test_models = [neuron_model_name for neuron_model_name in _neuron_models if neuron_model_name.endswith("nestml_unit_test")]

nest.ResetKernel()

for neuron_model in nestml_unit_test_models:
    nest.Create(neuron_model)

nest.Simulate(100)


